USE [cctv]

CREATE TABLE [dbo].[DESCONEXION](
	[DESCONEXION_ID] [int] IDENTITY(1,1) NOT NULL,
	[DISPOSITIVO_ID] [int] NOT NULL,
	[DESCONEXION_DATE] [datetime2](7) NOT NULL,
	[RECONEXION_DATE] [datetime2](7) NULL,
	[SCAN_ID] [int] NOT NULL,

PRIMARY KEY CLUSTERED 
(
	[DESCONEXION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[DESCONEXION] ADD  DEFAULT (switchoffset(sysdatetimeoffset(),'-03:00')) FOR [DESCONEXION_DATE]

ALTER TABLE [dbo].[DESCONEXION]  WITH CHECK ADD FOREIGN KEY([DISPOSITIVO_ID])
REFERENCES [dbo].[DISPOSITIVO] ([DISPOSITIVO_ID])

ALTER TABLE [dbo].[DESCONEXION]  WITH CHECK ADD FOREIGN KEY([SCAN_ID])
REFERENCES [dbo].[SCAN] ([SCAN_ID])

#######################################

CREATE TABLE [dbo].[DISPOSITIVO](
	[DISPOSITIVO_ID] [int] IDENTITY(1,1) NOT NULL,
	[SECTOR_ID] [int] NOT NULL,
	[SERVIDOR_ID] [int] NOT NULL,
	[MODELO_ID] [int] NOT NULL,
	[IP_ADDRESS] [varchar](250) NULL,
	[ES_PRESTADO] [bit] NOT NULL,
	[MAC_ADDRESS] [varchar](250) NULL,
	[NOMBRE] [varchar](250) NULL,
	[ALTA_DATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[DISPOSITIVO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [dbo].[DISPOSITIVO]  WITH CHECK ADD FOREIGN KEY([MODELO_ID])
REFERENCES [dbo].[MODELO] ([MODELO_ID])


ALTER TABLE [dbo].[DISPOSITIVO]  WITH CHECK ADD FOREIGN KEY([SECTOR_ID])
REFERENCES [dbo].[SECTOR] ([SECTOR_ID])


ALTER TABLE [dbo].[DISPOSITIVO]  WITH CHECK ADD FOREIGN KEY([SERVIDOR_ID])
REFERENCES [dbo].[SERVIDOR] ([SERVIDOR_ID])

#######################################

CREATE TABLE [dbo].[MARCA](
	[MARCA_ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](250) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MARCA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

#################################################

CREATE TABLE [dbo].[MODELO](
	[MODELO_ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](250) NOT NULL,
	[MARCA_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MODELO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MODELO]  WITH CHECK ADD FOREIGN KEY([MARCA_ID])
REFERENCES [dbo].[MARCA] ([MARCA_ID])
GO

###################################################

CREATE TABLE [dbo].[MOVIMIENTO_DISPOSITIVO](
	[MOVIMIENTO_ID] [int] NULL,
	[DISPOSITIVO_ID] [int] NULL,
	[SECTOR_DESTINO_ID] [int] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MOVIMIENTO_DISPOSITIVO]  WITH CHECK ADD FOREIGN KEY([DISPOSITIVO_ID])
REFERENCES [dbo].[DISPOSITIVO] ([DISPOSITIVO_ID])
GO

ALTER TABLE [dbo].[MOVIMIENTO_DISPOSITIVO]  WITH CHECK ADD FOREIGN KEY([MOVIMIENTO_ID])
REFERENCES [dbo].[MOVIMIENTOS] ([MOVIMIENTO_ID])
GO

ALTER TABLE [dbo].[MOVIMIENTO_DISPOSITIVO]  WITH CHECK ADD FOREIGN KEY([SECTOR_DESTINO_ID])
REFERENCES [dbo].[SECTOR] ([SECTOR_ID])
GO

##################################################################

CREATE TABLE [dbo].[MOVIMIENTOS](
	[MOVIMIENTO_ID] [int] IDENTITY(1,1) NOT NULL,
	[MOVIMIENTO_DATE] [datetime2](7) NOT NULL,
	[OBSERVACIONES] [varchar](250) NULL,
	[TIPO_MOVIMIENTO_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MOVIMIENTO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MOVIMIENTOS] ADD  DEFAULT (switchoffset(sysdatetimeoffset(),'-03:00')) FOR [MOVIMIENTO_DATE]
GO

ALTER TABLE [dbo].[MOVIMIENTOS]  WITH CHECK ADD FOREIGN KEY([TIPO_MOVIMIENTO_ID])
REFERENCES [dbo].[TIPOS_MOVIMIENTO] ([TIPO_MOVIMIENTO_ID])
GO

##################################################################

CREATE TABLE [dbo].[SCAN](
	[SCAN_ID] [int] IDENTITY(1,1) NOT NULL,
	[SCAN_DATE] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SCAN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SCAN] ADD  DEFAULT (switchoffset(sysdatetimeoffset(),'-03:00')) FOR [SCAN_DATE]
GO

##################################################################

CREATE TABLE [dbo].[SECTOR](
	[SECTOR_ID] [int] IDENTITY(1,1) NOT NULL,
	[SECTOR_NOMBRE] [varchar](250) NOT NULL,
	[SITIO_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SECTOR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SECTOR]  WITH CHECK ADD FOREIGN KEY([SITIO_ID])
REFERENCES [dbo].[SITIO] ([SITIO_ID])
GO

##################################################################

CREATE TABLE [dbo].[SERVIDOR](
	[SERVIDOR_ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](250) NOT NULL,
	[SITIO_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[SERVIDOR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SERVIDOR]  WITH CHECK ADD FOREIGN KEY([SITIO_ID])
REFERENCES [dbo].[SITIO] ([SITIO_ID])
GO

##################################################################

CREATE TABLE [dbo].[SITIO](
	[SITIO_ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](250) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SITIO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

########################################################################
